### ISSUE TITLE
ТрахеяMe

### ISSUE THREAD

**Issue by Krypt00n-1337** [LimerBoy/Inferno#2]
Шо це за пизда, де мій пітон. Сука ючдьб

**Comment by LimerBoy** [comment]
Пітон помер, тепер С хештег.

**Comment by Krypt00n-1337** [comment]
> Пітон помер, тепер С хештег.

Вьальутчдпдвьмькдчб...  Я сказав що ти пісюн, іди писати на пітоні або 1С

**Comment by Krypt00n-1337** [comment]
Взагалі я люблю маленьких дівчаток

**Comment by LimerBoy** [comment]
Я також
